apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: authentik
    name: in-cluster
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.10.1
    chart: authentik
    helm:
      values: |
        authentik:
          secret_key: authentik_csn
          postgresql:
            host: postgresql.postgresql.svc.cluster.local
            user: file:///postgres-creds/username
            password: file:///postgres-creds/password

        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
            hosts:
              - authentik.csnguyen.de
            tls:
              - secretName: csnguyen-tls
                hosts:
                  - authentik.csnguyen.de
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-postgres-credentials
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true

        worker:
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-postgres-credentials
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true

        redis:
          enabled: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
