apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    path: helm-charts/code-server
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
