apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.54.0
    chart: fluent
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
