apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.54.0
    chart: fluent-bit
    helm:
      values: |
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level {{ .Values.logLevel }}
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On

          ## https://docs.fluentbit.io/manual/pipeline/inputs
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Mem_Buf_Limit 100MB 
                Tag kube.*
                Mem_Buf_Limit 5MB
                Skip_Long_Lines On
                Refresh_Interval 30  # Longer interval
                # Exclude known high-volume namespaces if possible
                Exclude_Path /var/log/containers/*kube-system_*,/var/log/containers/*traefik_*

            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On

          ## https://docs.fluentbit.io/manual/pipeline/filters
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On

          ## https://docs.fluentbit.io/manual/pipeline/outputs
          outputs: |
            # opsensearch
            # [OUTPUT]
            #     Name es
            #     Match kube.*
            #     Host opensearch-cluster-master-headless.monitoring.svc.cluster.local
            #     Port 9200
            #     Logstash_Format On
            #     Retry_Limit False
            #     Buffer_Size 1MB
            #     # OpenSearch compatibility fixes
            #     Suppress_Type_Name On
            #     Generate_Id On
            # [OUTPUT]
            #     Name es
            #     Match host.*
            #     Host opensearch-cluster-master-headless.monitoring.svc.cluster.local
            #     Port 9200
            #     Logstash_Format On
            #     Logstash_Prefix node
            #     Retry_Limit False
            #     Buffer_Size 1MB
            #     # OpenSearch compatibility fixes
            #     Suppress_Type_Name On
            #     Generate_Id On

            [OUTPUT]
                Name gelf
                Match kube.*
                Host graylog-master.monitoring.svc.cluster.local 
                Port 12201
                Mode tcp
                Compress false
                Gelf_Short_Message_Key log
                Gelf_Timestamp_Key @timestamp
                Gelf_Host_Key kubernetes.pod_name

            [OUTPUT]
                Name gelf
                Match host.*
                Host graylog-master.monitoring.svc.cluster.local 
                Port 12201
                Mode tcp
                Compress false
                Gelf_Short_Message_Key MESSAGE

          ## https://docs.fluentbit.io/manual/pipeline/parsers
          customParsers: |
            [PARSER]
                Name docker_no_time
                Format json
                Time_Keep Off
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
