apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-addons
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 9.3.0
      chart: grafana/promtail
      helm:
        values: |
          config:
            lokiAddress: "http://loki-loki-distributed-gateway/loki/api/v1/push"
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 9.3.0
      chart: grafana/loki-distributed         
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true