apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-promtail
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.0
    chart: promtail
    helm:
      values: |
        config:
          clients:
            - url: "http://grafana-loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
          snippets:
            pipelineStages:
              - cri: {}
              - match:
                  selector: '{container="imaginary",namespace="prod"}'
                  action: drop
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
