apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.0
    chart: promtail      
    helm:
      values: |  
        config:
          lokiAddress: "http://grafana-loki-loki-distributed-gateway:3100/loki/api/v1/push"
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true