apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.80.5
    chart: loki-distributed
    helm:
      values: |
        loki:
          config: |
            chunk_store_config:
              max_look_back_period: 744h

            table_manager:
              retention_deletes_enabled: true
              retention_period: 744h
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
