apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.43.0
    chart: loki
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          readinessProbe:: {}
          persistence:
            enabled: true
            storageClassName: local-path
          storage:
            type: filesystem
        table_manager:
          retention_deletes_enabled: true
          retention_period: 720h
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
