apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.43.0
    chart: loki
    helm:
      values: |
        loki:
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          pattern_ingester:
            enabled: true
        limits_config:
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
          max_global_streams_per_user: 5000
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          retention_period: 168h # 7 days retention
          allow_structured_metadata: true
          volume_enabled: true
          ruler:
            enable_api: false

        minio:
          enabled: true

        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        lokiCanary:
          enabled: false
        gateway:
          enabled: false
        results_cache:
          enabled: false
        chunks_cache:
          enabled: false
        memcached:
          enabled: false
        memberlist:
          service:
            enabled: false

  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
