apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    targetRevision: 0.3.31
    chart: home-assistant
    helm:
      values: |
        configuration: true
          enabled: true
        hostNetwork: true
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: |
              kube-system-redirect-https@kubernetescrd
          hosts:
            - host: home-assistant.csnguyen.de
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: 
            - secretName: csnguyen-tls
              hosts:
                - home-assistant.csnguyen.de

  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
