apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jdownloader
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: https://sony2k20.github.io/service-deployer-helm
    targetRevision: 1.0.17
    chart: service-deployer
    helm:
      values: |
        fullnameOverride: jdownloader

        updateStrategy: Recreate

        dailyRestart:
          enabled: true
          schedule: "0 5 * * *"

        image:
          repository: jlesage/jdownloader-2
          tag: v25.07.2

        service:
          port: 5800
          
        ingress:
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: |
              kube-system-redirect-https@kubernetescrd
              kube-system-authentik-auth@kubernetescrd
          host: jdownloader.csnguyen.de

        startupProbe:
          httpGet:
            path: /
            port: 5800

        persistentVolume:
          - name: jdownloader-config
            mountPath: /config
          - name: jdownloader-downloads
            mountPath: /output

        resources:
          limits:
           cpu: 1000m
           memory: 1Gi
          requests:
           cpu: 100m
           memory: 128Mi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
