apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.15.1
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: "kube-system-redirect-https@kubernetescrd"
            hosts:
              - prometheus.csnguyen.de
            tls:
              - hosts:
                  - prometheus.csnguyen.de
                secretName: csnguyen-tls
        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: "kube-system-redirect-https@kubernetescrd"
            hosts:
              - grafana.csnguyen.de
            tls:
              - hosts:
                  - grafana.csnguyen.de
                secretName: csnguyen-tls
          sidecar:
            datasources:
              defaultDatasourceEnabled: true
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://grafana-loki-loki-distributed-query-frontend:3100
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true