apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 16.5.33
    helm:
      values: |
        auth:
          enabled: true
          databases: 
            - katy-coaching
          usernames:
            - admin  
          passwords:
            - admin
        service:
          type: LoadBalancer
          port: 27017
        externalAccess:
          enabled: true
          autoDiscovery:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true