apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ng-web-portfolio
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: https://sony2k20.github.io/service-deployer-helm
    targetRevision: 1.0.17
    chart: service-deployer
    helm:
      values: |
        fullnameOverride: ng-web-portfolio

        image:
          repository: sony2k20/ng-web-portfolio      
          tag: 555e917

        service:
          port: 80
          
        ingress:
          host: katy.csnguyen.de

        startupProbe:
          httpGet:
            path: /
            port: 80
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
