apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ng-web-blog
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: https://sony2k20.github.io/service-deployer-helm
    targetRevision: 1.0.0
    chart: service-deployer
    helm:
      values: |
        fullnameOverride: ng-web-blog

        image:
          repository: sony2k20/ng-web-blog   
        
        service:
          port: 80
          nodePort: 30004
          
        ingress:
          host: katy.csnguyen.de

        startupProbe:
          httpGet:
            path: /
            port: 80
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
