apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ng-web-portfolio
  namespace: argocd
  labels:
    type: app
  annotations:
    argocd-image-updater.argoproj.io/image-list: sony2k20/ng-web-portfolio:latest
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    path: helm-charts/ng-web-portfolio
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
