apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ng-web-blog
  namespace: argocd
  labels:
    type: app
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: "helm"
    argocd-image-updater.argoproj.io/image-list: ng-web-blog=sony2k20/ng-web-blog:latest
    argocd-image-updater.argoproj.io/ng-web-blog.helm.image-name: ng-web-blog.image.repository
    argocd-image-updater.argoproj.io/ng-web-blog.helm.image-tag: ng-web-blog.image.tag
    argocd-image-updater.argoproj.io/fooalias.update-strategy: digest
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    path: helm-charts/ng-web-blog
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
