apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: https://sony2k20.github.io/service-deployer-helm
    targetRevision: 1.0.7
    chart: service-deployer
    helm:
      values: |
        fullnameOverride: open-webui

        image:
          repository: ghcr.io/open-webui/open-webui
          tag: ollama
        
        service:
          port: 8080
          nodePort: 30012
          
        ingress:
          host: open-webui.csnguyen.de

        startupProbe:
          httpGet:
            path: /
            port: 8080

        resources:
          limits:
            cpu: 6000m
            memory: 15Gi
          requests:
            cpu: 100m
            memory: 128Mi
            
        persistentVolume:
          - name: open-webui
            mountPath: /app/backend/data
          - name: ollama
            mountPath: /root/.ollama
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
