apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 3.3.0
    chart: opensearch
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
