apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  labels:
    type: infra
spec:
  project: default
  source:
    path: helm-charts/pihole
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
