apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: https://sony2k20.github.io/endpoint-deployer-helm
    targetRevision: 1.0.3
    chart: endpoint-deployer
    helm:
      values: |
        fullnameOverride: pihole

        service:
          port: 80

        endpoint:
          ip: "192.168.178.99"

        ingress:
          host: pihole.csnguyen.de
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
