apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: "0.4.0"
    helm:
      values: |
        extraEnv:
          PLEX_CLAIM: "claim-kCK2eRXySEreGsfSz35v"
        image:
          registry: docker.io
          repository: linuxserver/plex
        ingress:
          enabled: true
          ingressClassName: traefik
          url: plex.csnguyen.de
          annotations: 
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
  destination:
    namespace: prod
    name: in-cluster
  syncPolicy:
    automated: 
      selfHeal: false
      prune: false
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
