apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    type: db
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.38
    helm:
      values: |
        image: 
          registry: docker.io
          repository: tensorchord/pgvecto-rs
          tag: pg16-v0.3.0
        # postgresqlSharedPreloadLibraries: vector
        primary:
          containerSecurityContext:
            readOnlyRootFilesystem: false
          initdb:
            scripts:
              create-extensions.sql: |
                CREATE EXTENSION cube;
                CREATE EXTENSION earthdistance;
                CREATE EXTENSION vectors;        
        global:
          # security:
          #   allowInsecureImages: true
          postgresql:
            auth:
              username:	admin
              password: admin
              database: immich
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true