apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: https://sony2k20.github.io/service-deployer-helm
    targetRevision: 1.0.23
    chart: service-deployer
    helm:
      values: |
        fullnameOverride: seerr
        image:
          repository: ghcr.io/seerr-team/seerr
          tag: latest
          pullPolicy: Always
        ingress: 
          host: seerr.csnguyen.de
        persistentVolume:
          - name: seerr
            mountPath: /app/config
        service:
          port: 5055
          nodePort: 30018
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
