apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: ghcr.io/seerr-team/seerr
    chart: seerr-chart
    targetRevision: 3.7.0
    helm:
      values: |
        fullnameOverride: seerr
        config:
          persistence:
            existingClaim: seerr
        service:
          type: NodePort
          nodePort: 30018
        ingress:
          enabled: true
          className: traefik
          annotations: 
            # cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.middlewares: |
              kube-system-redirect-https@kubernetescrd
          path: /
          hosts:
            - host: seerr.csnguyen.de
              paths:
                - path: /
                  pathType: Prefix
          tls: 
          - secretName: csnguyen-tls
            hosts:
              - seerr.csnguyen.de
        securityContext:
              privileged: false
              runAsNonRoot: false    # Erlaubt es, als Root zu starten
              runAsUser: 0           # Setzt die User-ID auf Root (0)
              runAsGroup: 0          # Setzt die Gruppen-ID auf Root (0)
              allowPrivilegeEscalation: true # Erlaubt dem Prozess, Root-Rechte zu behalten
              readOnlyRootFilesystem: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
