apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    repoURL: https://sony2k20.github.io/service-deployer-helm
    targetRevision: 1.0.17
    chart: service-deployer
    helm:
      values: |
        fullnameOverride: stirling-pdf

        image:
          repository: docker.stirlingpdf.com/stirlingtools/stirling-pdf
          tag: latest

        service:
          port: 8080
          nodePort: 30011
          
        ingress:
          host: pdf.csnguyen.de

        startupProbe:
          httpGet:
            path: /
            port: 8080
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
