apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: traefik
    name: in-cluster
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 36.3.0
    helm:
      values: |
        ports:
          web:
            port: 80
            expose: true
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 443
            expose: true
            exposedPort: 443
            protocol: TCP
        service:
          type: LoadBalancer
          annotations: {}
          spec:
            ports:
              - name: web
                port: 80
                targetPort: 80
              - name: websecure
                port: 443
                targetPort: 443
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"        
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true