apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: traefik
    name: in-cluster
  project: default
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/traefik/helm/traefik
    chart: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
