apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://helm.irsigler.cloud
    chart: uptime-kuma
    targetRevision: '2.19.3'
    helm:
      values: |
        volume:
          enabled: true
          existingClaim: uptime-kuma
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
          className: traefik
          hosts:
            - host: uptime-kuma.csnguyen.de
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: uptime-kuma
              hosts:
                - uptime-kuma.csnguyen.de
  destination:
    namespace: prod
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
