apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    path: helm-charts/uptime-kuma
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  destination:
    namespace: prod
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
