apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upsnap
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    path: helm-charts/upsnap
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
