nextcloud:
  nextcloud:
    host: nextcloud.csnguyen.de
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
      tokenKey: ""
      smtpUsernameKey: smtp-username
      smtpPasswordKey: smtp-password
      smtpHostKey: smtp-host
  ingress:
    enabled: true
    className: traefik
    annotations: 
      traefik.ingress.kubernetes.io/redirect-entry-point: "web"
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: |
        kube-system-redirect-https@kubernetescrd
    tls:
      - secretName: csnguyen-tls
        hosts:
          - nextcloud.csnguyen.de
  persistence:
    enabled: true
    existingClaim: nextcloud
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: true
  extraInitContainers:
    - name: install-ffmpeg
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args: ["apk add --no-cache ffmpeg && cp /usr/bin/ffmpeg /usr/bin/ffprobe /tmp/"]
      volumeMounts:
        - name: ffmpeg-bin
          mountPath: /tmp/
  extraVolumeMounts:
    - name: ffmpeg-bin
      mountPath: /usr/bin/ffmpeg
      subPath: ffmpeg
    - name: ffmpeg-bin
      mountPath: /usr/bin/ffprobe
      subPath: ffprobe
  extraVolumes:
    - name: ffmpeg-bin
      emptyDir: {}