nextcloud:
  nextcloud:
    host: nextcloud.csnguyen.de
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
      tokenKey: ""
      smtpUsernameKey: smtp-username
      smtpPasswordKey: smtp-password
      smtpHostKey: smtp-host
    extraInitContainers:
      - name: install-ffmpeg
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache ffmpeg
            mkdir -p /tmp/ffmpeg-bin /tmp/ffmpeg-lib
            cp /usr/bin/ffmpeg /usr/bin/ffprobe /tmp/ffmpeg-bin/
            cp /usr/lib/*.so* /tmp/ffmpeg-lib/
        volumeMounts:
          - name: ffmpeg-bin
            mountPath: /tmp/ffmpeg-bin
          - name: ffmpeg-lib
            mountPath: /tmp/ffmpeg-lib
    extraVolumeMounts:
      - name: ffmpeg-bin
        mountPath: /usr/bin/ffmpeg
        subPath: ffmpeg
      - name: ffmpeg-bin
        mountPath: /usr/bin/ffprobe
        subPath: ffprobe
      - name: ffmpeg-lib
        mountPath: /usr/lib/ffmpeg
        mountPropagation: Bidirectional
    extraVolumes:
      - name: ffmpeg-bin
        emptyDir: {}
      - name: ffmpeg-lib
        emptyDir: {}
    extraEnv:
      - name: LD_LIBRARY_PATH
        value: /usr/lib/ffmpeg:/usr/lib/x86_64-linux-gnu

  ingress:
    enabled: true
    className: traefik
    annotations: 
      traefik.ingress.kubernetes.io/redirect-entry-point: "web"
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: |
        kube-system-redirect-https@kubernetescrd
    tls:
      - secretName: csnguyen-tls
        hosts:
          - nextcloud.csnguyen.de
  persistence:
    enabled: true
    existingClaim: nextcloud
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: true