nextcloud:
  imaginary:
    enabled: true
  collabora:
    enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/redirect-entry-point: "web"
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: |
          kube-system-redirect-https@kubernetescrd
      hosts: office.csnguyen.de
      tls:
        - secretName: csnguyen-tls
          hosts:
            - nextcloud.csnguyen.de
    collabora:
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: collabora-username
        passwordKey: collabora-password
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: db-username
      passwordKey: db-password
      hostKey: db-host
      databaseKey: db-name
  redis:
    enabled: true
    auth:
      enabled: false
    image:
      repository: bitnamilegacy/redis
      tag: 8.2
  # image:
  #   tag: "31.0.9"
  nextcloud:
    configs:
      config.php: |
        <?php
        $CONFIG = array (
          'trusted_domains' => 
          array (
            0 => 'localhost',
            1 => 'nextcloud.csnguyen.de',
            2 => 'office.csnguyen.de',
            3 => 'son-server.tail1334c6.ts.net',
          ),
          'trusted_proxies' => 
          array (
            0 => '10.0.0.0/0',
          ),
          'overwriteprotocol' => 'https',
          'overwritehost' => 'nextcloud.csnguyen.de',
          'overwrite.cli.url' => 'https://nextcloud.csnguyen.de',
          'enabledPreviewProviders' => 
          array (
            0 => 'OC\\Preview\\Imaginary',
          ),
          'preview_imaginary_url' => 'nextcloud-imaginary.prod.svc.cluster.local',
          'custom_worker_domain' => 'office.csnguyen.de', 
        );
    mail:
      enabled: true
      fromAddress: kontakt
      domain: csnguyen.de
      secure: ssl
      port: 465
    host: nextcloud.csnguyen.de
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
      tokenKey: ""
      smtpUsernameKey: smtp-username
      smtpPasswordKey: smtp-password
      smtpHostKey: smtp-host
    extraInitContainers:
      - name: install-ffmpeg
        image: alpine:latest
        command:
          # [
          #   "sh",
          #   "-c",
          #   "echo 'Starting FFmpeg installation...' && wget -q https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz && tar xf ffmpeg*.tar.xz && cp ffmpeg*/ffmpeg ffmpeg*/ffprobe /tmp/ && echo 'FFmpeg installation completed successfully'",
          # ]
          [
            "sh",
            "-c",
            "apk update && apk add --no-cache ffmpeg && cp $(which ffmpeg) $(which ffprobe) /tmp/ && echo 'FFmpeg installation completed successfully'",
          ]
        volumeMounts:
          - name: ffmpeg-bin
            mountPath: /tmp/
    extraVolumeMounts:
      - name: ffmpeg-bin
        mountPath: /usr/local/bin/ffmpeg
        subPath: ffmpeg
      - name: ffmpeg-bin
        mountPath: /usr/local/bin/ffprobe
        subPath: ffprobe
    extraVolumes:
      - name: ffmpeg-bin
        emptyDir: {}

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/redirect-entry-point: "web"
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: |
        kube-system-redirect-https@kubernetescrd
    tls:
      - secretName: csnguyen-tls
        hosts:
          - nextcloud.csnguyen.de
  persistence:
    enabled: true
    existingClaim: nextcloud
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: true
