nextcloud:
  nextcloud:
    host: nextcloud.csnguyen.de
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
      tokenKey: ""
      smtpUsernameKey: smtp-username
      smtpPasswordKey: smtp-password
      smtpHostKey: smtp-host
    extraSidecarContainers:
      - name: ffmpeg
        image: linuxserver/ffmpeg
        volumeMounts:
          - name: ffmpeg-bin
            mountPath: /output
        command: ["/bin/sh", "-c"]
        args: ["cp /usr/bin/ffmpeg /usr/bin/ffprobe /output/"]

    extraVolumeMounts:
      - name: ffmpeg-bin
        mountPath: /usr/bin/ffmpeg
        subPath: ffmpeg
      - name: ffmpeg-bin
        mountPath: /usr/bin/ffprobe
        subPath: ffprobe

    extraVolumes:
      - name: ffmpeg-bin
        emptyDir: {}

  ingress:
    enabled: true
    className: traefik
    annotations: 
      traefik.ingress.kubernetes.io/redirect-entry-point: "web"
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: |
        kube-system-redirect-https@kubernetescrd
    tls:
      - secretName: csnguyen-tls
        hosts:
          - nextcloud.csnguyen.de
  persistence:
    enabled: true
    existingClaim: nextcloud
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: true