apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Sony2k20/gitops-deployments.git
        revision: HEAD
        directories:
          - path: app-of-apps/apps/*
  template:
    metadata:
      name: "{{path.basename}}"
      labels:
        type: config
    spec:
      project: default
      source:
        repoURL: "https://github.com/Sony2k20/gitops-deployments.git"
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
