apiVersion: v1
kind: Service
metadata:
    name: {{ include "flatnotes.fullname" . }}-ts
    labels:
        app.kubernetes.io/name: {{ include "flatnotes.fullname" . }}
spec:
    type: NodePort
    ports:
        - port: {{ .Values.service.port }}
          targetPort: {{ .Values.service.port }}
          protocol: TCP
          nodePort: 30007
    selector:
        app.kubernetes.io/name: {{ include "flatnotes.fullname" . }}