apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  labels:
    type: db
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 16.5.40
    helm:
      values: |
        persistence:
          existingClaim: mongodb
        auth:
          enabled: true
          databases: 
            - graylog
            - katy
          usernames:
            - graylog
            - katy
          existingSecret: mongodb-secret
        service:
          type: LoadBalancer
          port: 27017
        externalAccess:
          enabled: true
          autoDiscovery:
            enabled: true
        # Add security context settings here
        securityContext:
          enabled: true
          runAsUser: 1001
          fsGroup: 1001
        # Ensure the container runs as non-root
        containerSecurityContext:
          runAsNonRoot: true
          runAsUser: 1001
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
