apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    type: db
spec:
  project: default
  source:
    path: helm-charts/postgresql
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
