service:
  port: 80
  containerPort: 8000

endpoint:
  ip: "192.168.2.109"

ingress:
  host: omv.csnguyen.de
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: "vpn"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd
