service:
  port: 80
  containerPort: 8888

endpoint:
  ip: "192.168.178.100"

ingress:
  host: omv.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd
