{{- if .Values.persistentVolume }}
{{- range .Values.persistentVolume }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .storage }} 
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  hostPath:
    path: {{ .hostPath }}
  persistentVolumeReclaimPolicy: Retain
{{- end }}
{{- end }}