{{- if .Values.persistentVolume }}
{{- range .Values.persistentVolume }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  storageClassName: manual
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .storage }} 
  selector:
    matchLabels:
      name: {{ .name }}
{{- end }}
{{- end }}