apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    name: python
spec:
  containers:
  - name: python
    image: python:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /home/data
  volumes:
  - name: data
    hostPath:
      path: /srv/dev-disk-by-uuid-4c7807a3-ad92-4a02-921b-5414abc40250/kubernetes/utils
      type: Directory 