apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    name: python
spec:
  containers:
  - name: python
    image: python:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /home/data
  volumes:
  - name: data
    hostPath:
      path: /srv/dev-disk-by-uuid-1637aef4-f2aa-4ea3-98e4-3e31d5c4f6ae/NAS/utils
      type: Directory 