apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    name: python
spec:
  containers:
  - name: python
    image: python:3.11
    command: ["/bin/bash", "-c"]
    args:
      - |
        apt update && \
        apt install -y pipx ffmpeg && \
        pipx ensurepath && \
        sleep infinity
    volumeMounts:
    - mountPath: /home/data
      name: data
  volumes:
  - name: data
    hostPath:
      path: /srv/dev-disk-by-uuid-4c7807a3-ad92-4a02-921b-5414abc40250/kubernetes/utils
      type: Directory