apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    name: python
spec:
  containers:
  - name: python
    image: python:3.11
    command: ["/bin/bash", "-c"]
    args:
      - |
        apt update && \
        apt install -y pipx ffmpeg gcc python3-dev && \
        pipx ensurepath && \
        sleep infinity
    volumeMounts:
    - mountPath: /home/data
      name: data
  volumes:
  - name: data
    hostPath:
      path: /srv/dev-disk-by-uuid-1f2204f1-efe5-4e04-a2a2-b4598f7b17db/data/kubernetes/utils
      type: Directory