apiVersion: v1
kind: Pod
metadata:
  name: utils
  labels:
    name: utils
spec:
  containers:
  - name: utils
    image: arunvelsriram/utils:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /home/data
      name: data
  volumes:
  - name: data
    hostPath:
      path: /srv/dev-disk-by-uuid-4c7807a3-ad92-4a02-921b-5414abc40250/kubernetes/utils
      type: Directory 