jellyfin:
  image:
    tag: "10.10"

  service:
    port: 8096
    nodePort: 30000

  ingress:
    enabled: true
    annotations: 
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: |
        kube-system-redirect-https@kubernetescrd
    path: /
    hosts:
      - jellyfin.csnguyen.de
    tls: 
    - secretName: csnguyen-tls
      hosts:
        - jellyfin.csnguyen.de

  persistence:
    config:
      enabled: true
      existingClaim: jellyfin-config
      subPath: Kubernetes/jellyfin
    media:
      enabled: true
      existingClaim: jellyfin-media
      subPath: Media

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi