jellyfin:
  image:
    tag: "10.10"

  service:
    port: 8096
    nodePort: 30000

  ingress:
    enabled: true
    className: traefik
    annotations: 
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: |
        kube-system-redirect-https@kubernetescrd
    path: /
    hosts:
      - host: jellyfin.csnguyen.de
        paths:
          - path: /
            pathType: Prefix
    tls: 
    - secretName: csnguyen-tls
      hosts:
        - jellyfin.csnguyen.de

  persistence:
    config:
      enabled: true
      existingClaim: jellyfin-config
    media:
      enabled: true
      existingClaim: jellyfin-media

  volumes: 
    - name: dri
      hostPath:
        path: /dev/dri

  volumeMounts: 
    - name: dri
      mountPath: /dev/dri
  
  securityContext:
    privileged: true