apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-ts
spec:
  type: NodePort
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
      nodePort: 30006
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server