apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-restart
spec:
  schedule: "0 5 * * *" # At 5:00 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl delete pod -l app={{ .Chart.Name }}
          restartPolicy: OnFailure
