apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod
  name: cronjob-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: cronjob-sa-jellyfin
  namespace: prod
roleRef:
  kind: Role
  name: cronjob-role
  apiGroup: rbac.authorization.k8s.io
