apiVersion: v1
kind: Service
metadata:
  name: {{ template "jellyfin.fullname" . }}-ts
spec:
  type: NodePort
  ports:
    - port: {{ .Values.jellyfin.service.port }}
      targetPort: http
      nodePort: {{ .Values.jellyfin.service.nodePort }}
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}