apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ng-web-portfolio.fullname" . }}
  labels:
    {{- include "ng-web-portfolio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ng-web-portfolio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        deploymentTime: "2024-12-22 10:26:10"
      labels:
        {{- include "ng-web-portfolio.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: EMAIL_SERVER_URL
              value: {{ .Values.env.emailServerUrl }}
            - name: EMAIL_SERVER_URL
              value: {{ .Values.env.emailAdress }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
