apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ng-web-portfolio.fullname" . }}-ts
  labels:
    {{- include "ng-web-portfolio.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: tailscale
  rules:
    - host: {{.Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ng-web-portfolio.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
       - {{.Values.ingress.host }}
      secretName: csnguyen-tls