apiVersion: v1
kind: Service
metadata:
  name: {{ include "ng-web-portfolio.fullname" . }}-ts
  labels:
    {{- include "ng-web-portfolio.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30005
  selector:
    {{- include "ng-web-portfolio.selectorLabels" . | nindent 4 }}
