apiVersion: v1
kind: Service
metadata:
  name: {{ template "immich.fullname" . }}-ts
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}