immich:
  immich:
    metrics:
      # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
      enabled: false
    persistence:
      library:
        existingClaim: immich
  redis:
    enabled: true
  env:
    DB_HOSTNAME: "postgresql.postgresql.svc.cluster.local:5432"
    DB_USERNAME: test
    DB_DATABASE_NAME: my_new_db
    DB_PASSWORD: test

service:
  port: 2283
  nodePort: 30009
ingress:
  className: traefik
  annotations: 
    traefik.ingress.kubernetes.io/client-max-body-size: "0"
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd
  path: /
  host: immich.csnguyen.de
  tls: 
  - secretName: csnguyen-tls
    hosts:
      - immich.csnguyen.de

