argo-cd:
  dex:
    enabled: false
  global:
    domain: argocd.csnguyen.de
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: |
          kube-system-redirect-https@kubernetescrd
        traefik.ingress.kubernetes.io/redirect-entry-point: web
      tls: 
        secretName: csnguyen-tls
  configs:
    params:
      server.insecure: true
    cm:
      exec.enabled: true
