apiVersion: v1
kind: Service
metadata:
  name: {{ include "upsnap.fullname" . }}-ts
  labels:
    {{- include "upsnap.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      nodePort: 30102
  selector:
    {{- include "upsnap.selectorLabels" . | nindent 4 }}
