replicaCount: 1

image:
  repository: ghcr.io/seriousm4x/upsnap
  pullPolicy: IfNotPresent
  tag: 5.0.4

service:
  type: ClusterIP
  port: 8090
  containerPort: 8090

ingress:
  host: upsnap.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

persistentVolume:
  - name: upsnap
    namespace: prod
    storage: 500Mi
    hostPath: /srv/dev-disk-by-uuid-1f2204f1-efe5-4e04-a2a2-b4598f7b17db/data/kubernetes/upsnap
    accessModes:
      - ReadWriteMany 

startupProbe:
  httpGet:
    path: /
    port: 8090