replicaCount: 1

image:
  repository: ghcr.io/seriousm4x/upsnap
  pullPolicy: IfNotPresent
  tag: 5.0.4

service:
  type: ClusterIP
  port: 8090
  containerPort: 8090

ingress:
  host: upsnap.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

startupProbe:
  httpGet:
    path: /
    port: 8090