apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-grafana-ts
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
  selector:
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/name: grafana