apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-portfolio.fullname" . }}
  labels:
    {{- include "web-portfolio.labels" . | nindent 4 }}
  annotations:
    tailscale.com/expose: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "web-portfolio.selectorLabels" . | nindent 4 }}
