apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-ts
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: 30002
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
