apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nestjs-email-service.fullname" . }}
  labels:
    {{- include "nestjs-email-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nestjs-email-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        deploymentTime: "2025-03-30 20:09:39"
      labels:
        {{- include "nestjs-email-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          {{- with .Values.env }}
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}

          {{- with .Values.envSecrets }}
          {{- $secretName := .secretKeyRef }}
          {{- range $key, $value := .name }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $value }}
          {{- end }}
          {{- end }}                                              
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}