apiVersion: v1
kind: Service
metadata:
  name: {{ include "nestjs-email-service.fullname" . }}-ts
  labels:
    {{- include "nestjs-email-service.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30009
  selector:
    {{- include "nestjs-email-service.selectorLabels" . | nindent 4 }}
