# fullnameOverride: kube-prometheus

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
  grafana:
    sidecar:
      datasources:
        defaultDatasourceEnabled: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-loki-distributed-query-frontend.monitoring:3100
        dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kubernetes-dashboard:
          gnetId: 18283
          revision: 1 
          datasource: Prometheus

promtail:
  config:
    lokiAddress: "http://loki-loki-distributed-gateway/loki/api/v1/push"