apiVersion: v1
kind: Service
metadata:
  name: nextcloud-ts
  namespace: prod
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud