apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "portainer.fullname" . }}
subsets:
  - addresses:
      - ip: {{ .Values.endpoint.ip }} # The external IP
    ports:
      - port: {{ .Values.service.containerPort }}     # The external port on the IP