service:
  port: 80
  containerPort: 9000

endpoint:
  ip: "192.168.178.99"

ingress:
  host: portainer.csnguyen.de
  path: /
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd
