replicaCount: 1

image:
  name: sony2k20/nestjs-email-service
  pullPolicy: Always
  tag: latest

github:
  repo: "https://github.com/Sony2k20/nestjs-email-service"
  branch: "master"

service:
  type: ClusterIP
  port: 3000

ingress:
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "10"
    # traefik.ingress.kubernetes.io/rewrite-target: /$2
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd
      kube-system-strip-api-prefix@kubernetescrd
  hosts:
    - host: katy.csnguyen.de
      paths:
        - path: /api(/|$)
          pathType: ImplementationSpecific
  tls:
    - secretName: csnguyen-tls
      hosts:
        - katy.csnguyen.de

livenessProbe:
  httpGet:
    path: /health
    port: 3000
readinessProbe:
  httpGet:
    path: /health
    port: 3000
