replicaCount: 1

image:
  name: sony2k20/nestjs-email-service
  pullPolicy: Always
  tag: latest

github:
  repo: "https://github.com/Sony2k20/nestjs-email-service"
  branch: "master"

service:
  type: ClusterIP
  port: 3000


env:
  NODE_ENV: test

envSecrets:
  secretKeyRef: email-service-secrets
  name:
    SMTP_HOST: SMTP_HOST
    SMTP_PORT: SMTP_PORT
    SMTP_USER: SMTP_USER
    SMTP_PASS: SMTP_PASS

ingress:
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd,
      kube-system-strip-api-prefix@kubernetescrd
  hosts:
    - host: katy.csnguyen.de
      paths:
        - path: /api
          pathType: Prefix
  tls:
    - secretName: csnguyen-tls
      hosts:
        - katy.csnguyen.de

livenessProbe:
  httpGet:
    path: /health
    port: 3000
readinessProbe:
  httpGet:
    path: /health
    port: 3000
