replicaCount: 1

image:
  name: sony2k20/nestjs-email-service
  pullPolicy: Always
  tag: latest

github:
  repo: "https://github.com/Sony2k20/nestjs-email-service"
  branch: "master"

service:
  type: ClusterIP
  port: 3000

ingress:
  host: email.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

livenessProbe:
  httpGet:
    path: /docs
    port: 3000
readinessProbe:
  httpGet:
    path: /docs
    port: 3000
