apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server
  labels:
    name: code-server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/dev-disk-by-uuid-4c7807a3-ad92-4a02-921b-5414abc40250/kubernetes/code-server
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
