fullnameOverride: jdownloader

replicaCount: 1

image:
  repository: jlesage/jdownloader-2
  pullPolicy: Always
  tag: latest

github:
  repo: "https://github.com/Sony2k20/jdownloader"
  branch: "master"

# env: 
#   KEY: value

# envSecrets: 
#   secretsName: secret-name
#   secrets:
#     KEY: value

service:
  type: ClusterIP
  port: 5800

ingress:
  host: jdownloader.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

startupProbe:
  httpGet:
    path: /
    port: 5800

persistentVolume:
  - name: jdownloader-config
    storage: 1Gi
    disk: disk1
    hostPath: /srv/dev-disk-by-uuid-1f2204f1-efe5-4e04-a2a2-b4598f7b17db/kubernetes/jdownloader
    accessModes:
      - ReadWriteMany 
    mountPath: /config
  - name: jdownloader-downloads
    storage: 300Gi
    disk: disk2
    hostPath: /srv/dev-disk-by-uuid-1f2204f1-efe5-4e04-a2a2-b4598f7b17db/data
    accessModes:
      - ReadWriteMany 
    mountPath: /Downloads