fullnameOverride: jdownloader

replicaCount: 1

image:
  repository: jlesage/jdownloader-2
  pullPolicy: Always
  tag: latest

github:
  repo: "https://github.com/Sony2k20/jdownloader"
  branch: "master"

# env: 
#   KEY: value

# envSecrets: 
#   secretsName: secret-name
#   secrets:
#     KEY: value

service:
  type: ClusterIP
  port: 5800

ingress:
  host: jdownloader.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

startupProbe:
  httpGet:
    path: /
    port: 5800

persistentVolume:
  - name: jdownloader-config
    mountPath: /config
    subPath: Kubernetes/jdownloader
  - name: jdownloader-downloads
    mountPath: /output
    subPath: /Downloads

resources: 
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
