apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    type: app
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: helm-charts/argocd
    repoURL: https://github.com/Sony2k20/gitops-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
