apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  labels:
    type: app
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/latest
    targetRevision: 2.11.3
    chart: rancher
    helm:
      values: |
        replicas: 1
        hostname: rancher.csnguyen.de
        ingress:
          enabled: true
          includeDefaultExtraAnnotations: false
          extraAnnotations: 
            traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
          ingressClassName: traefik
          tls:
            source: secret
            secretName: csnguyen-tls
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
