apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "omv.fullname" . }}
  annotations:
    admission.gatekeeper.sh/ignore: "true" 
subsets:
  - addresses:
      - ip: {{ .Values.endpoint.ip }} # The external IP
    ports:
      - port: {{ .Values.service.containerPort }}     # The external port on the IP