apiVersion: v1
kind: Service
metadata:
  name: {{ include "ng-web-blog.fullname" . }}-ts
  labels:
    {{- include "ng-web-blog.labels" . | nindent 4 }}
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30004
  selector:
    {{- include "ng-web-blog.selectorLabels" . | nindent 4 }}
