apiVersion: v1
kind: Service
metadata:
  name: {{ include "comfyui.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerPort }}
  clusterIP: None