replicaCount: 1

image:
  repository: sony2k20/ng-web-blog
  pullPolicy: Always
  tag: latest

github:
  repo: "https://github.com/Sony2k20/ng-web-blog"
  branch: "master"

service:
  type: ClusterIP
  port: 80

ingress:
  host: blog.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

startupProbe:
  httpGet:
    path: /
    port: 80
