fullnameOverride: web-portfolio

replicaCount: 1

image:
  name: nginx
  pullPolicy: IfNotPresent
  tag: latest

github:
  repo: "https://github.com/Sony2k20/web-portfolio"
  branch: "master"

service:
  type: NodePort
  nodePort: 30002
  port: 80

ingress:
  host: csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

startupProbe:
  httpGet:
    path: /
    port: 80
