service:
  port: 8080

image:
  repository: dullage/flatnotes
  tag: v5.4.1
  pullPolicy: IfNotPresent

ingress:
  host: notes.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd




