postgresql:
  primary.persistence.existingClaim: postgresql
  global.postgresql.auth.username: joplin	
  global.postgresql.auth.database: joplin
  global.postgresql.auth.existingSecret: joplin-db-secret	
  global.postgresql.auth.secretKeys.adminPasswordKey:	POSTGRES_PASSWORD
  global.postgresql.auth.secretKeys.userPasswordKey: POSTGRES_PASSWORD
  global.postgresql.auth.secretKeys.replicationPasswordKey: POSTGRES_PASSWORD

service:
  port: 22300

image:
  repository: florider89/joplin-server
  tag: 3.0.1
  pullPolicy: IfNotPresent

ingress:
  host: notes.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd




