joplin:
  image:
    repository: joplin/server
    tag: 3.0.15
    pullPolicy: IfNotPresent

  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: |
          kube-system-redirect-https@kubernetescrd
      hosts:
        - host: notes.csnguyen.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: csnguyen-tls
          hosts:
            - notes.csnguyen.de

  env:
    TZ: UTC
    APP_BASE_URL: https://notes.csnguyen.de
    APP_PORT: 22300
    DB_CLIENT: pg
    POSTGRES_HOST: joplin-postgresql
    POSTGRES_PORT: 5432
    POSTGRES_DATABASE: joplin
    POSTGRES_USER: joplin
    POSTGRES_PASSWORD: joplin-pass

  postgresql:
    enabled: true
    postgresqlUsername: joplin
    postgresqlPassword: joplin-pass
    postgresqlDatabase: joplin
    persistence:
      enabled: true
      # storageClass: ""
