postgresql:
  primary:
    persistence:
      existingClaim: postgresql
  auth:
    username: joplin
    database: joplin
    existingSecret: joplin-db-secret
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
      replicationPasswordKey: POSTGRES_PASSWORD
      
service:
  port: 22300

image:
  repository: florider89/joplin-server
  tag: 3.0.1
  pullPolicy: IfNotPresent

ingress:
  host: notes.csnguyen.de
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd




