postgresql:
  primary.persistence.existingClaim: postgresql
  global.postgresql.auth.username: joplin	
  global.postgresql.auth.database: joplin
  global.postgresql.auth.existingSecret: joplin-db-secret	
  global.postgresql.auth.secretKeys.adminPasswordKey:	POSTGRES_PASSWORD
  global.postgresql.auth.secretKeys.userPasswordKey: POSTGRES_PASSWORD
  global.postgresql.auth.secretKeys.replicationPasswordKey: POSTGRES_PASSWORD

service:
  port: 80

image:
  repository: florider89/joplin-server
  tag: 3.0.1
  pullPolicy: IfNotPresent

ingress:
  main:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: |
        kube-system-redirect-https@kubernetescrd
    hosts:
      - host: notes.csnguyen.de
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: csnguyen-tls
        hosts:
          - notes.csnguyen.de




