apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ include "homepage.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "homepage.fullname" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "homepage.fullname" . }}
subjects:
    - kind: ServiceAccount
      name: {{ include "homepage.fullname" . }}
      namespace: {{ .Values.namespace }}