apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "homepage.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "homepage.fullname" . }}
secrets:
    - name: {{ include "homepage.fullname" . }}