apiVersion: v1
kind: Service
metadata:
    name: {{ include "homepage.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "homepage.fullname" . }}
spec:
    type: NodePort
    ports:
        - port: 3000
          targetPort: http
          protocol: TCP
          name: http
          nodePort: 30003
    selector:
        app.kubernetes.io/name: {{ include "homepage.fullname" . }}