apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin-config
data:
  TZ: UTC
  APP_PORT: {{ .Values.service.port }}
  DB_CLIENT: pg
  POSTGRES_HOST: joplin-postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: joplin
  POSTGRES_USER: joplin