apiVersion: v1
kind: Service
metadata:
  name: {{ include "joplin.fullname" . }}
  labels:
    {{- include "joplin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "joplin.selectorLabels" . | nindent 4 }}
