apiVersion: v1
kind: Service
metadata:
    name: {{ include "joplin.fullname" . }}-ts
    labels:
        app.kubernetes.io/name: {{ include "joplin.fullname" . }}
spec:
    type: NodePort
    ports:
        - port: 22300
          targetPort: http
          protocol: TCP
          nodePort: 30007
    selector:
        app.kubernetes.io/name: {{ include "joplin.fullname" . }}