fullnameOverride: pigallery2

replicaCount: 1

image:
  name: bpatrik/pigallery2
  pullPolicy: Always
  tag: latest

env:
  NODE_ENV: production 

envSecrets: {}

service:
  type: ClusterIP
  port: 80

ingress:
  host: gallery.csnguyen.de
  path: /
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

startupProbe:
  httpGet:
    path: /
    port: 80
