fullnameOverride: ng-web-portfolio

replicaCount: 1

image:
  name: sony2k20/ng-web-portfolio
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  host: katy.csnguyen.de
  path: /
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd

startupProbe:
  httpGet:
    path: /
    port: 80
