uptime-kuma:
  volume:
    enabled: false
  additionalVolumes:
    - name: storage
      persistentVolumeClaim:
        claimName: uptime-kuma
  additionalVolumeMounts:
    - mountPath: /app/data
      subPath: /Kubernetes/uptime-kuma
      name: storage 
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
    className: traefik
    hosts:
      - host: uptime-kuma.csnguyen.de
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: csnguyen-tls
        hosts:
          - uptime-kuma.csnguyen.de
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi