fullnameOverride: k3s-config

namespaces:
  - prod

persistentVolume:
  - name: homelab-pv
    storage: 7Ti
    hostPath: /srv/dev-disk-by-uuid-1f2204f1-efe5-4e04-a2a2-b4598f7b17db/data/Kubernetes
    accessModes:
      - ReadWriteOnce 

persistentVolumeClaim:
  - name: jdownloader-config
    namespace: prod
    storage: 1Gi    
    accessModes:
      - ReadWriteOnce 