apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "pihole.fullname" . }}
    release: {{ include "pihole.fullname" . }}
  name: pihole-dns
  namespace: prod
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: dns
      port: {{ .Values.pihole.serviceDns.port }}
      protocol: TCP
      targetPort: dns
    - name: dns-udp
      port: {{ .Values.pihole.serviceDns.port }}
      protocol: UDP
      targetPort: dns-udp
  selector:
    app: {{ include "pihole.fullname" . }}
    release: {{ include "pihole.fullname" . }}
  type: LoadBalancer