apiVersion: v1
kind: Service
metadata:
  name: piholergocd-ts
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30101
  selector:
    app: pihole
    release: pihole